--1st query
SELECT COUNT(*) AS FEMALECOUNT
FROM AIRLINE
WHERE GENDER = 'Female';
--END

--2nd query
SELECT COUNT(*) AS PASSENGERCOUNT
FROM AIRLINE
WHERE CLASS = 'Business';
--END

--3rd query
SELECT COUNT(*) AS EC0_PASSENGER
FROM AIRLINE
WHERE CLASS = 'Eco';
--END

--4th query
SELECT COUNT(*) AS KID_COUNT
FROM AIRLINE
WHERE AGE<13;
--END

--5th query
SELECT COUNT(*) AS ADULT_COUNT
FROM AIRLINE
WHERE AGE>16 AND CLASS='Business';
--END

